pull_request_rules:
  - name: automatic squash
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=buildkite/plaidml-plaidml/pr
      - base=master
    actions:
      merge:
        method: squash
        strict: smart

  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
