package(default_visibility = ["//visibility:public"])

exports_files([
    "googlemock.LICENSE",
    "version.tpl.cc",
    "version.tpl.py",
])

config_setting(
    name = "with_callgrind",
    define_values = {"with_callgrind": "true"},
)
