# Copyright 2019 Intel Corporation.

load("//pmlc:lit.bzl", "glob_lit_tests")

glob_lit_tests(
    data = [
        "//pmlc/tools/pmlc-tblgen",
        "@llvm-project//mlir:OpBaseTdFiles",
        "@llvm-project//mlir:include/mlir/Interfaces/SideEffectInterfaces.td",
    ],
    default_tags = ["manual"],
)
