env:
  PIPELINE: "plaidml"

steps:
  - block: "Verify public contribution. Accept this PR?"
    branches: "*:*"

  - command: "PYTHONPATH=$$PWD python ci/buildkite.py | buildkite-agent pipeline upload"
    label: ":pipeline:"
    agents:
      PLATFORM: linux_x86_64
