# Copyright 2021 Intel Corporation

load("//pmlc:lit.bzl", "glob_lit_tests")

package(default_visibility = ["//visibility:public"])

# Disable LevelZero tests as runtime needs runtime device as argument
#glob_lit_tests(
#  data = ["//pmlc/rt/level_zero:level_zero_probe"],
#)
