# Copyright 2019 Intel Corporation.

load("//bzl:plaidml.bzl", "plaidml_cc_library")

package(default_visibility = ["//visibility:public"])

plaidml_cc_library(
    name = "tile",
    deps = [
        "//pmlc/dialect/tile/ir",
        "//pmlc/dialect/tile/transforms",
    ],
)
