# Copyright 2019 Intel Corporation.

load("//vendor/mlir:tblgen.bzl", "gentbl")

package(default_visibility = ["//visibility:public"])

# gentbl(
#     name = "gen",
#     tbl_outs = [
#         (
#             "-gen-cpp-impl",
#             "oplib_impl.h.inc",
#         ),
#         (
#             "-gen-cpp-wrappers",
#             "oplib_wrappers.h.inc",
#         ),
#         (
#             "-gen-py-wrappers",
#             "oplib_wrappers.py",
#         ),
#     ],
#     tblgen = "//pmlc/tools/pmlc-tblgen",
#     td_file = "ops.td",
# )
