package(default_visibility = ["//visibility:public"])

exports_files([
    "analysis.yml",
    "buildkite.yml",
    "ml_gpu.yml",
    "plaidml.yml",
    "pytorch.yml",
    "sphinx.yml",
    "tensorflow.yml",
    "unix.yml",
    "windows.yml",
])
