sp = "&nbsp;&nbsp;&nbsp;&nbsp;"
br = "<br>"
code_open = "<code>"
code_close = "</code>"
code_tensor_dim = "<font class=\"code-tensor-dim\">"
code_tensor_index = "<font class=\"code-tensor-index\">"
code_directive = "<font class=\"code-directive\">"
code_numeric = "<font class=\"code-numeric\">"
code_function_name = "<font class=\"code-function-name\">"
code_input_param = "<font class=\"code-input-param\">"
code_output_param = "<font class=\"code-output-param\">"
font_close = "</font>"
