# Copyright 2020 Intel Corporation
package(default_visibility = ["//visibility:public"])

load("//bzl:plaidml.bzl", "plaidml_cc_library")

plaidml_cc_library(
    name = "comp",
    deps = [
        "//pmlc/dialect/comp/ir",
    ],
)
