# Copyright 2019 Intel Corporation.

load("//pmlc:lit.bzl", "glob_lit_tests")

glob_lit_tests(
    tags_override = {
        "load-store.mlir": ["manual"],
        "parallel_for.mlir": ["manual"],
    },
)
