# Copyright 2019 Intel Corporation.

package(default_visibility = ["//visibility:public"])

load("//bzl:plaidml.bzl", "plaidml_py_library")

plaidml_py_library(
    name = "py_setup",
    srcs = ["__init__.py"],
)
