env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

steps:
# build phase

{{#variants}}
  - label: ':hammer_and_wrench: {{emoji}}'
    command: '{{python}} ci/buildkite.py build {{name}}'
    agents:
      PLATFORM: '{{name}}'
{{/variants}}

  - wait

# test phase

{{#tests}}
  - label: '{{emoji}}{{engine}}{{shard_emoji}}{{suite}}/{{workload}}/{{platform}} BATCH_SIZE={{batch_size}}'
    command: |
      {{python}} -m pip install pyyaml --user
      {{python}} ci/buildkite.py test \
        {{platform}} {{suite}} {{workload}} {{batch_size}} {{#shard}}--shard-count {{count}} --shard {{id}}{{/shard}}

  {{#soft_fail}}
    soft_fail: true
  {{/soft_fail}}
    timeout_in_minutes: {{timeout}}
  {{#retry}}
    retry:
      automatic:
        limit: {{.}}
  {{/retry}}
    agents:
      PLATFORM: '{{platform}}'
{{/tests}}

  - wait: ~
    continue_on_failure: true

# report phase

  - label: ':bar_chart:'
    command: python3 ci/buildkite.py report
    agents:
      PLATFORM: linux_x86_64
    retry:
      manual:
        permit_on_passed: true
