env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

steps:

{{#actions}}
  - label: '{{vars.emoji}}{{name}}'
    key: '{{vars.key}}'
  {{#vars.depends_on}}
    depends_on: '{{.}}'
  {{/vars.depends_on}}
    command: |
    {{#cmds}}
      {{.}}
    {{/cmds}}
  {{#vars.soft_fail}}
    soft_fail: true
  {{/vars.soft_fail}}
  {{#vars.timeout}}
    timeout_in_minutes: {{.}}
  {{/vars.timeout}}
    agents:
      PLATFORM: '{{vars.platform}}'
    artifact_paths:
  {{#vars.artifacts}}
      - '{{.}}'
  {{/vars.artifacts}}

{{/actions}}

  - wait: ~
    continue_on_failure: true

  - label: ':bar_chart:'
    command: |
      echo --- :buildkite: Downloading artifacts
      buildkite-agent artifact download ci/test/**/* .
      PYTHONPATH=$$PWD python ci/report.py ci
      cat ci/report/annotate.html | buildkite-agent annotate --style=$$(cat ci/report/status.txt)
    agents:
      PLATFORM: linux_x86_64
    retry:
      manual:
        permit_on_passed: true
    artifact_paths:
      - ci/report/**/*
