env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

steps:
# build phase

{{#variants}}
  - label: ':hammer_and_wrench: {{emoji}}'
    command: '{{python}} ci/buildkite.py build {{name}}'
    key: '{{name}}'
    agents:
      PLATFORM: '{{name}}'
    artifact_paths:
      {{#artifacts}}
      - "tmp/build/**/*"
      {{/artifacts}}
      - "bazel-testlogs/**/test.log"
{{/variants}}
  
  - label: ':hammer_and_wrench: :linux: :beer:'
    key: linux_x86_64_cmake
    command: |
      echo --- :building_construction: configuration
      python configure --ci --temp=/tmp/$${BUILDKITE_AGENT_NAME}/plaidml

      echo --- :hammer_and_wrench: ninja
      ninja -C build-x86_64/Release

      echo --- :hammer_and_wrench: ninja check-test
      ninja -C build-x86_64/Release check-test

  - label: 'IRv10 models'
    trigger: irv10
    soft_fail: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "fe0679141cff310ca0662ae65223dc86b491b469"
      env:
        PLAIDML_COMMIT: "${BUILDKITE_COMMIT}"
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"


# test phase


{{#tests}}
  - label: '{{emoji}}{{engine}}{{shard_emoji}}{{suite}}/{{workload}}/{{platform}} BATCH_SIZE={{batch_size}}'
    command: |
      {{python}} -m pip install pyyaml --user
      {{python}} ci/buildkite.py test {{platform}} {{suite}} {{workload}} {{batch_size}} {{#shard}}--shard-count {{count}} --shard {{id}}{{/shard}}
    depends_on: {{variant}}

  {{#soft_fail}}
    soft_fail: true
  {{/soft_fail}}
    timeout_in_minutes: {{timeout}}
  {{#retry}}
    retry:
      automatic:
        limit: {{.}}
  {{/retry}}
    agents:
      PLATFORM: '{{platform}}'
    artifact_paths:
      - "tmp/test/**/report.json"
{{/tests}}

  - wait: ~
    continue_on_failure: true

# report phase

  - label: ':bar_chart:'
    command: python3 ci/buildkite.py report
    agents:
      PLATFORM: linux_x86_64
    retry:
      manual:
        permit_on_passed: true
