@startuml high_level_overview
scale 1600*900
skinparam rectangle {
  roundCorner 25
}
rectangle "Keras" {
component "plaidml_keras"
}
rectangle "ONNX" {
component onnx_plaidml
}
rectangle "PlaidML" as pml {
  component "Python Interface" {
    interface "Op API" as opapi
    component "Op Lib" as oplib
    interface "API" as pyapi
    opapi -> oplib
    oplib ..> pyapi
  }
  rectangle "PlaidML Core" {
    interface "c/c++ API" as pmlapi
    component "Runtime" as runtime {
      component "Tile Compiler"  as compiler {
        component "Tile Parser" as parser
        component "Tile Optimizer" as optimizer
        component "IR CodeGen" as codegen
      }
      component "Platform" as platform {
        () "API" as platapi
        frame "Memory Strategies"
      }
      parser -> optimizer 
      optimizer -> codegen
      compiler ..> platapi
    }
    rectangle "HALs" as hals {
      () "API" as halapi
      component "OpenCL" as oclhal <<hal>>
      component "LLVM" as llvmhal <<hal>>
    }
    platform -> halapi
    halapi ..> oclhal
    halapi ..> llvmhal
    runtime - pmlapi
  }
  pyapi ..> pmlapi
}

onnx_plaidml ..> pyapi
plaidml_keras ..> pyapi
onnx_plaidml ..>  opapi
plaidml_keras ..> opapi
@enduml