# Copyright 2020 Intel Corporation

load("//bzl:plaidml.bzl", "plaidml_cc_library")

package(default_visibility = ["//visibility:public"])

plaidml_cc_library(
    name = "affinex",
    deps = [
        "//pmlc/dialect/affinex/transforms",
    ],
)
