package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "protoc-gen-cc11",
    srcs = ["protoc-gen-cc11.cc"],
    copts = ["-std=c++11"],
    deps = ["@com_google_protobuf//:protoc_lib"],
)
